services:
  app:
    build: .
    environment:
      - DOCKERIZED=true
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASS=12345
      - DB_NAME=testdb
    depends_on:
      - postgres

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=testdb
